services:
  - type: web
    name: burako-online
    builder: NIXPACKS
    env: node
    plan: starter
    region: oregon
    # build/start configured below (Nixpacks builder provides a more hermetic install)
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: CLIENT_ORIGINS
        value: https://burako-online.onrender.com,http://localhost:5173
      - key: DATABASE_URL
        value: "<set-in-render-dashboard>"
      - key: VITE_SERVER_URL
        value: "<set-in-render-dashboard>"
      - key: NPM_CONFIG_OPTIONAL
        value: "false"
    # Use npm ci for reproducible installs under Nixpacks; keep NPM_CONFIG_OPTIONAL=false as guard
    buildCommand: npm ci && npm run build --workspace=client && npm run build --workspace=server
    startCommand: npm run start --workspace=server
