services:
  - type: web
    name: burako-server
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build --workspace=server
    startCommand: npm run start --workspace=server
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: CLIENT_ORIGINS
        value: https://burako-client.onrender.com,http://localhost:5173
      - key: DATABASE_URL
        value: replace-with-render-postgres-url
  - type: static_site
    name: burako-client
    buildCommand: npm install && npm run build --workspace=client
    publishPath: client/dist
    envVars:
      - key: VITE_SERVER_URL
        value: https://burako-server.onrender.com
