services:
  - type: web
    name: burako-app
    env: node
    plan: free
    region: oregon
    # build both client and server, producing server/dist and client/dist
    buildCommand: npm install && npm run build --workspace=client && npm run build --workspace=server
    # start the server (server will serve client/dist statically)
    startCommand: npm run start --workspace=server
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: CLIENT_ORIGINS
        value: https://burako-online.onrender.com,http://localhost:5173
      - key: DATABASE_URL
        value: replace-with-render-postgres-url
      - key: VITE_SERVER_URL
        value: https://burako-online.onrender.com
